name: node-rtsp-player
region: nyc
services:
  - environment_slug: node-js
    github:
      branch: main
      deploy_on_push: true
      repo: devrsc/node-rtsp-player
    name: web
    routes:
      - path: /
    run_command: node server.js
    source_dir: /
    build_command: |
      apt-get update && apt-get -y install ffmpeg
